trigger:
- main
   
pool:
  #vmImage: 'ubuntu-latest'
  name: 'Default'
   

variables:
  imageName: 'pipelines-javascript-docker'
  dockerHub: 'd59b2975-0ffd-4e5a-a575-348bcdfbcb43'
  imageRepository: 'wissenravikatrenikonapipelinesjavascriptdocker'
  containerRegistry: 'akshandsonlab002.azurecr.io'
  DOCKER_BUILDKIT: 1
    
steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: app/Dockerfile
    
- task: Docker@2
  displayName: Push image
  inputs:
    containerRegistry: |
       $(dockerHub)
    repository: $(imageName)
    command: push
    tags: |
      test1
      test2
