trigger:
- main
   
pool:
  vmImage: 'ubuntu-latest'
   

variables:
  imageName: 'pipelines-javascript-docker'
  DOCKER_BUILDKIT: 1
    
steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: app/Dockerfile
    
- task: Docker@2
  displayName: Push image
  inputs:
    containerRegistry: |
       $(dockerHub)
     repository: $(imageName)
    command: push
    tags: |
      test1
      test2
